import Head from 'next/head'
import Form from '../components/Form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dark:bg-slate-800 flex justify-center items-center m-auto h-screen flex-col'>
        <Form />
      </main>
    </>
  )
}
